spring:
  application:
    name: bookingservice
  datasource:
    url: "jdbc:mysql://localhost:3306/ticketing"
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: booking
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

inventory:
  service:
    url: "http://localhost:8080/api/v1/inventory"

server:
  port: 8081

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"